import test from 'node:test';
import assert from 'node:assert/strict';
import {backend} from './apps-script.test.mjs';
function fixture(){const b=backend();b.ctx.setupClasses();b.sheets.Teachers.appendRow(['a@las.ch','Teacher A','yes']);b.sheets.Teachers.appendRow(['b@las.ch','Teacher B','yes']);return b;}
function call(b,email,route,p={}){return b.request(b.login(email),{route:'classes.'+route,...p});}
function create(b,email='a@las.ch',id='request-123',extra={}){return call(b,email,'create',{name:'Class one',start:'2026-09-01',end:'2026-10-01',requestId:id,...extra});}
test('class creation is teacher-only, retry-safe and role revocation is immediate',()=>{const b=fixture();assert.equal(create(b,'s@las.ch').error,'teacher-required');const c=create(b);assert.equal(c.ok,true);assert.match(c.code,/^[A-Z0-9]{4}(-[A-Z0-9]{4}){2}$/);assert.equal(create(b).classInfo.id,c.classInfo.id);assert.equal(b.sheets.Classes.rows.length,2);assert.equal(call(b,'b@las.ch','rotate',{classId:c.classInfo.id}).error,'class-unavailable');b.sheets.Teachers.rows[1][2]='no';assert.equal(call(b,'a@las.ch','rotate',{classId:c.classInfo.id}).error,'teacher-required');assert.equal(call(b,'s@las.ch','preview',{code:c.code}).error,'invalid-code');});
test('joining requires confirmed identity, is idempotent and never returns diary or roster',()=>{const b=fixture(),c=create(b),p={code:c.code,classId:c.classInfo.id};assert.equal(call(b,'s@las.ch','join',p).error,'bad-value');assert.equal(call(b,'s@las.ch','join',{...p,confirm:true}).ok,true);assert.equal(call(b,'s@las.ch','join',{...p,confirm:true}).ok,true);assert.equal(b.sheets.Memberships.rows.length,2);let state=call(b,'s@las.ch','state');assert.equal(state.memberships.length,1);assert.equal(state.summariesEnabled,false);assert.doesNotMatch(JSON.stringify(state),/account|@las.ch|codeHash|nights|energy/);assert.equal(call(b,'other@las.ch','state').memberships.length,0);call(b,'other@las.ch','leave',{classId:c.classInfo.id});assert.equal(call(b,'s@las.ch','state').memberships.length,1);call(b,'s@las.ch','leave',{classId:c.classInfo.id});assert.equal(call(b,'s@las.ch','state').memberships.length,0);});
test('overlapping membership, expired/rotated codes, and excessive guessing are rejected',()=>{const b=fixture(),a=create(b),c=create(b,'b@las.ch');call(b,'s@las.ch','join',{code:a.code,classId:a.classInfo.id,confirm:true});assert.equal(call(b,'s@las.ch','join',{code:c.code,classId:c.classInfo.id,confirm:true}).error,'membership-overlap');call(b,'a@las.ch','rotate',{classId:a.classInfo.id});assert.equal(call(b,'s@las.ch','preview',{code:a.code}).error,'invalid-code');let payload=JSON.parse(b.sheets.Classes.rows[2][1]);payload.expires=0;b.sheets.Classes.rows[2][1]=JSON.stringify(payload);assert.equal(call(b,'s@las.ch','preview',{code:c.code}).error,'invalid-code');for(let i=0;i<20;i++)call(b,'guess@las.ch','preview',{code:'AAAA-AAAA-AAAA'});assert.equal(call(b,'guess@las.ch','preview',{code:a.code}).error,'try-later');});
test('comparison needs two teachers, matching dates, separate code and bilateral revoke',()=>{const b=fixture(),a=create(b),c=create(b,'b@las.ch');const invite=call(b,'a@las.ch','invite',{classId:a.classInfo.id});assert.equal(call(b,'s@las.ch','previewComparison',{code:invite.code}).error,'teacher-required');assert.equal(call(b,'s@las.ch','preview',{code:invite.code}).error,'invalid-code');assert.equal(call(b,'a@las.ch','accept',{code:invite.code,classId:a.classInfo.id,sourceId:a.classInfo.id,confirm:true}).error,'comparison-unavailable');const p={code:invite.code,classId:c.classInfo.id,sourceId:a.classInfo.id,confirm:true};assert.equal(call(b,'b@las.ch','accept',p).ok,true);const state=call(b,'b@las.ch','state');assert.equal(state.comparisons[0].status,'accepted');assert.equal(state.summariesEnabled,false);assert.equal(call(b,'a@las.ch','invite',{classId:a.classInfo.id}).error,'comparison-unavailable');assert.equal(call(b,'b@las.ch','revoke',{comparisonId:state.comparisons[0].id}).ok,true);});
test('archive removes memberships and invitations; mismatched periods cannot compare',()=>{const b=fixture(),a=create(b),c=create(b,'b@las.ch','another-id',{end:'2026-10-02'});const invite=call(b,'a@las.ch','invite',{classId:a.classInfo.id});assert.equal(call(b,'b@las.ch','accept',{code:invite.code,classId:c.classInfo.id,sourceId:a.classInfo.id,confirm:true}).error,'period-mismatch');call(b,'s@las.ch','join',{code:a.code,classId:a.classInfo.id,confirm:true});assert.equal(call(b,'a@las.ch','archive',{classId:a.classInfo.id}).ok,true);assert.equal(call(b,'s@las.ch','state').memberships.length,0);assert.equal(call(b,'b@las.ch','previewComparison',{code:invite.code}).error,'invalid-code');});
